target 'Dynamic' do
inhibit_all_warnings!
pod 'SDWebImage', '~> 4.4.6'
pod 'AFNetworking', '~> 3.2.1'
pod 'YYModel', '~> 1.0.4'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'MJRefresh', '~> 3.1.15.7'
pod 'Masonry', '~> 1.1.0'
pod 'Qiniu', '~> 7.2.5'
pod 'AMap3DMap', '~> 6.7.0'
pod 'AMapLocation', '~> 2.6.1'
pod 'AMapSearch', '~> 6.6.0'
pod 'YBImageBrowser', '~> 2.1.4'
end
